import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";
import Providers from "./provider";
import Header from "@/components/Header";
import { Toaster } from "@/components/ui/toaster"

const playfairDisplay = Playfair_Display({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mosaic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={playfairDisplay.className}>
        <Providers>
          <header>
            <Header/>
          </header>
          <main >{children}</main>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
